# Generated by Django 5.1.5 on 2025-04-15 16:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('blood_sugar', 'Blood Sugar'), ('weight', 'Weight'), ('temperature', 'Temperature'), ('heart_rate', 'Heart Rate'), ('oxygen_saturation', 'Oxygen Saturation'), ('respiratory_rate', 'Respiratory Rate'), ('height', 'Height'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('measurement_date', models.DateField()),
                ('measurement_time', models.TimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chart Data',
                'verbose_name_plural': 'Chart Data',
                'ordering': ['-measurement_date', '-measurement_time'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('medical_report', 'Medical Report'), ('imaging', 'Imaging'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], max_length=20)),
                ('document_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Health Issue',
                'verbose_name_plural': 'Health Issues',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('result', models.TextField()),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Logbook Entry',
                'verbose_name_plural': 'Logbook Entries',
                'ordering': ['-entry_date', '-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('boolean', 'Boolean'), ('categorical', 'Categorical')], default='numeric', max_length=20)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('reference_range_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Parameter Definition',
                'verbose_name_plural': 'Parameter Definitions',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parameter Value',
                'verbose_name_plural': 'Parameter Values',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('recorded_date', models.DateField()),
                ('recorded_time', models.TimeField()),
                ('duration', models.CharField(blank=True, help_text="e.g., '2 hours', '3 days'", max_length=100)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['-recorded_date', '-recorded_time'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Test Type',
                'verbose_name_plural': 'Test Types',
            },
        ),
    ]
