# Generated by Django 5.1.5 on 2025-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='vital_signs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
