services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Map Vite development server port
    volumes:
      - ./frontend:/app  # Mount local code
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Map Django server port
    volumes:
      - ./backend:/app  # Mount local code
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "python /app/wait_for_db.py && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Map MySQL port
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:  # Named volume for MySQL persistence
