# Generated by Django 5.1.5 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
