# Generated by Django 5.1.5 on 2025-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
