# Generated by Django 5.1.5 on 2025-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_before_minutes', models.PositiveIntegerField(choices=[(5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (1440, '1 day before')], default=30, help_text='How many minutes before medication time to send notification')),
                ('scheduled_time', models.DateTimeField(help_text='When the notification is scheduled to be sent')),
                ('notification_time', models.DateTimeField(blank=True, help_text='When the notification was actually sent', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('message', models.TextField(help_text='The notification message')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this notification is enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_medication_name', models.CharField(blank=True, help_text='Used when medication is not in database', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for taking the medication', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('effective_date', models.DateField()),
                ('effective_time', models.TimeField()),
                ('schedule_type', models.CharField(choices=[('when_needed', 'When Needed'), ('daily', 'Daily'), ('every_x_days', 'Every X Days'), ('specific_days', 'Specific Days of Week'), ('cycle', 'Take X days and Rest Y days')], max_length=50)),
                ('every_x_days', models.PositiveIntegerField(blank=True, help_text="For 'Every X Days' schedule", null=True)),
                ('specific_days_of_week', models.JSONField(blank=True, help_text="['mon','wed','fri']", null=True)),
                ('cycle_active_days', models.PositiveIntegerField(default=0, help_text='Days to take medication in cycle')),
                ('cycle_rest_days', models.PositiveIntegerField(default=0, help_text='Days to rest in cycle')),
                ('frequency_type', models.CharField(choices=[('times_per_day', 'X Times a Day'), ('every_x_hours', 'Every X Hours')], default='times_per_day', max_length=50)),
                ('times_per_day', models.PositiveIntegerField(default=1)),
                ('every_x_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('exact_times', models.JSONField(blank=True, help_text='["08:00", "14:00"]', null=True)),
                ('dose_amount', models.CharField(help_text="e.g., '10mg', '1 tablet'", max_length=100)),
                ('duration_type', models.CharField(choices=[('ongoing', 'Ongoing'), ('for_x_days', 'For X Days'), ('until_date', 'Until Date')], default='ongoing', max_length=50)),
                ('number_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notification_time', models.PositiveIntegerField(choices=[(0, 'No notification'), (5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (1440, '1 day before')], default=30, help_text='When to send notification before medication time')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled for this medication plan')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(help_text='The time to take this medication')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for specific day schedules', null=True)),
                ('is_daily', models.BooleanField(default=False, help_text='Whether this time applies to every day')),
                ('is_active_cycle_day', models.BooleanField(default=True, help_text='Whether this time is for active cycle days or rest days')),
                ('day_in_cycle', models.PositiveIntegerField(blank=True, help_text="The day in the cycle (1-based) for 'every X days' schedule", null=True)),
                ('dose_override', models.CharField(blank=True, help_text='Override dose for this specific time if different from plan', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_link', models.URLField(blank=True, help_text='Link to external page with medication details (e.g., medex.com.bd)', max_length=500, null=True)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('inhaler', 'Inhaler'), ('drops', 'Drops'), ('powder', 'Powder'), ('other', 'Other')], max_length=50)),
                ('strength', models.CharField(help_text='e.g., 500mg, 50ml, etc.', max_length=100)),
                ('unit', models.CharField(choices=[('mg', 'Milligram'), ('g', 'Gram'), ('ml', 'Milliliter'), ('mcg', 'Microgram'), ('IU', 'International Unit'), ('other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('analgesic', 'Analgesic'), ('antibiotic', 'Antibiotic'), ('antiviral', 'Antiviral'), ('antihistamine', 'Antihistamine'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antiinflammatory', 'Anti-inflammatory'), ('vitamin', 'Vitamin'), ('supplement', 'Supplement'), ('other', 'Other')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['generic_name'], name='medications_generic_f50273_idx'), models.Index(fields=['brand_name'], name='medications_brand_n_7fa3be_idx'), models.Index(fields=['category'], name='medications_categor_d82bd0_idx'), models.Index(fields=['is_active'], name='medications_is_acti_ebfb5f_idx')],
            },
        ),
    ]
