# Generated by Django 5.1.5 on 2025-04-15 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0002_initial'),
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='health_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_plans', to='medical_records.healthissue'),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationnotification',
            name='medication_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='medications.medicationplan'),
        ),
        migrations.AddField(
            model_name='medicationtime',
            name='medication_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_times', to='medications.medicationplan'),
        ),
    ]
