# Generated by Django 5.1.5 on 2025-04-11 08:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `medications_medicationtime` (
                `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                `created_at` datetime(6) NOT NULL,
                `updated_at` datetime(6) NOT NULL,
                `time` time(6) NOT NULL,
                `day_of_week` integer NULL,
                `is_daily` bool NOT NULL,
                `is_active_cycle_day` bool NOT NULL,
                `day_in_cycle` integer UNSIGNED NULL,
                `dose_override` varchar(100) NULL,
                `notes` longtext NULL,
                `medication_plan_id` bigint NOT NULL,
                CONSTRAINT `medications_medicati_medication_plan_id_c6d15c8e_fk_medicatio` FOREIGN KEY (`medication_plan_id`) REFERENCES `medications_medicationplan` (`id`)
            );
            """,
            """
            DROP TABLE IF EXISTS `medications_medicationtime`;
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX `medications_medicationtime_time_34024445` ON `medications_medicationtime` (`time`);
            """
        ),
    ]
