# Generated by Django 5.1.5 on 2025-04-15 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinician',
            name='specializations',
            field=models.ManyToManyField(related_name='clinicians', to='clinicians.specialization'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clinician__isnull', False), ('diagnostic_center__isnull', True)), models.Q(('clinician__isnull', True), ('diagnostic_center__isnull', False)), _connector='OR'), name='review_either_clinician_or_center'),
        ),
    ]
